title: Safari Cookie Cleaner
description: A focused, delete-only cookie cleaner for Safari on macOS and iOS.
url: https://lunatech.github.io
baseurl: /safariCookieCleaner
theme: jekyll-theme-cayman
show_downloads: false
